### ISSUE TITLE
Transfer kernelspy

### ISSUE THREAD

**Issue by vidartf** [jupyterlab-contrib/jupyterlab-contrib.github.io#1]
# Target
This extension adds a button in the notebook toolbar, which opens a window that lets you inspect all messages going to/from the kernel.

- The code repository: https://github.com/vidartf/jupyterlab-kernelspy
- The npm package on npmjs.com (if available): jupyterlab-kernelspy
- The python package on pypi.org (if available): jupyterlab-kernelspy
- The conda-forge recipe on https://github.com/conda-forge (if available): N/A
- The documentation website (if available): N/A

# Reason
To increase the bus factor to more than 1.

# Checklist

- [x] You are owner of the repository you want to transfer
- Your role in the transferred repository will be (check one of):
  - [ ] Maintainer of all `jupyterlab-contrib` repositories
  - [ ] Maintainer of the transferred repository only
  - [x] Either is fine (I'm not usre I understand the difference)
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

**Note:** Is there a requirement that everyone with commit rights have 2FA enabled?

**Comment by fcollonval** [comment]
Thanks @vidartf for the proposal and the comments. 

I invite you as owner in this organization so you can transfer the project.
I also invite you on the npmjs jlab-contrib organization. So you should be able to add the jupyterlab-kernelspy to it (https://www.npmjs.com/settings/jlab-contrib/packages).
For pypi.org, could you add me as co-owner of the package, please (my id is fcollonval).

> Your role in the transferred repository will be (check one of):    Either is fine (I'm not usre I understand the difference)

The idea is to know your level of contribution: none, only that project or on all projects within the organization.
I will change the wording to clarify it.

> Note: Is there a requirement that everyone with commit rights have 2FA enabled?

Yes it is required.

**Comment by vidartf** [comment]
> I also invite you on the npmjs jlab-contrib organization. So you should be able to add the jupyterlab-kernelspy to it 

I have received the invite, but I'm unsure about how to complete this step. Will this put the extension in the `@jlab_contrib` scope ?

**Comment by fcollonval** [comment]
Thanks for transferring the project and granting me access to the pypi project.

> Will this put the extension in the @jlab_contrib scope ?

No, the concept of organization on npmjs is really great (I'ld love to have something similar for pypi...):
https://docs.npmjs.com/about-organization-scopes-and-packages#managing-unscoped-packages

This is really great for this use case, as we can manage access to a team without the burden of renaming the extensions - see for example https://www.npmjs.com/package/@jlab-enhanced/cell-toolbar for which you became collaborators by joining @jlab-contrib.

You should be able to add the package for kernelspy from that page: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access

**Comment by vidartf** [comment]
I'm sorry, but I don't see any ways to add a package to that organization. Either I'm missing a button, or it is different for owners vs members. Would you mind giving some more detailed instructions (e.g. a screenshot) so we can confirm?

**Comment by fcollonval** [comment]
> Either I'm missing a button, or it is different for owners vs members. 

You are correct. I think I needed to increase the default status given to new member. You should no be admin.

> Would you mind giving some more detailed instructions (e.g. a screenshot) so we can confirm?

That [page](https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access) looks like this for me:

![image](https://user-images.githubusercontent.com/8435071/104559632-f26e1e80-5644-11eb-9264-9c8e9cd98417.png)

To add an existing package, you need to type its name in the input box next to _+ Add existing package_ button. Then click on that button.

**Comment by vidartf** [comment]
I have added the package to the org now. If there are any other steps to be taken, please let me know, if not, I think we can close the issue :)

**Comment by fcollonval** [comment]
Thanks @vidartf - one last request - could you please switch the right on the package from **read** to **read/write** (on the same page) to all publication by team members? And we should be all set 

> I'll push a new version following the update to the latest JLab 3 structure to check the rights.

**Comment by vidartf** [comment]
I thought I had, but it seems not. Now it should be?

**Comment by fcollonval** [comment]
Awesome thanks @vidartf
