### ISSUE TITLE
Request for transferring the jupyterlab-logout repository into jupyterlab-contrib

### ISSUE THREAD

**Issue by ocordes** [jupyterlab-contrib/jupyterlab-contrib.github.io#13]
# Target
A Logout Button for JupyterLab useful when used with JupyterHub!

- The code repository: https://github.com/jtpio/jupyterlab-logout

# Reason
It is a useful extension for JupyterLab when you are working with JupyterHub. The Logout Menu button is deep in the menu structure ... 

# Checklist

- [ ] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [X] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [X] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [X] The code is available under a Open Source license
- [X] A license file is present in the code repository
- [X] The extension is working on at least JupyterLab 2.x
- [X] The repository contains a README file describing:
  - [X] The provided feature(s)
  - [ ] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [X] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [ ] I certify the extension is not using exclusively paid-plan of any commercial service
- [ ] I will help the transfer process on the code repository AND the built packages

I put @jtpio into the issue, he is the owner of the repository!

**Comment by jtpio** [comment]
Thanks @ocordes for opening this :+1: 

Happy to proceed with the move to this organization. Since `jupyterlab-logout` depends on it, we might as well want to move [jupyterlab-topbar](https://github.com/jtpio/jupyterlab-topbar) too.

**Comment by fcollonval** [comment]
> we might as well want to move [jupyterlab-topbar](https://github.com/jtpio/jupyterlab-topbar) too.

Indeed that may be a good idea. @jtpio you should have the proper rights to transfer the project in this organization.

**Comment by jtpio** [comment]
Moved: https://github.com/jupyterlab-contrib/jupyterlab-logout

Follow-up issue: https://github.com/jupyterlab-contrib/jupyterlab-logout/issues/6

@ocordes would you like to be added as a collaborator to the repo?

**Comment by ocordes** [comment]
Yes, I'm happy to join! Thanx for moving!

**Comment by jtpio** [comment]
Nice, thanks!

I opened https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/14 to move `jupyterlab-topbar`.

**Comment by jtpio** [comment]
Closing as fixed, thanks all!

**Comment by fcollonval** [comment]
@jtpio you should have received an invitation to join jlab-contrib organization on npmjs.

Could you accept it so you can add the npm packages on that organization (ping me before as I need to increase your rights once you accepted the invitation).

Link to add a package to the organization: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access

**Comment by jtpio** [comment]
Thanks @fcollonval, I just accepted the invite.

**Comment by fcollonval** [comment]
Great I updated your rights. So you should now be able to add the package to the organization: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access

**Comment by jtpio** [comment]
Done, thanks!
