### ISSUE TITLE
Move `jupyterlab-topbar`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#14]
# Target

- The code repository: https://github.com/jtpio/jupyterlab-topbar
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab-topbar
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-topbar/
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyterlab-topbar-feedstock
- The documentation website (if available):

# Reason

- Better visibility
- `jupyterlab-logout` depends on it: https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/13

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @jtpio. 

You can transfer the project in this organization.

**Comment by jtpio** [comment]
Done: https://github.com/jupyterlab-contrib/jupyterlab-topbar

Also added you to the PyPI package: https://pypi.org/project/jupyterlab-topbar/

And added the packages to the `npm` organization.

Conda forge feedstock update: https://github.com/conda-forge/jupyterlab-topbar-feedstock/pull/2

**Comment by jtpio** [comment]
Closing as fixed, thanks!
