### ISSUE TITLE
Move jupyter-videochat repo to this org

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab-contrib/jupyterlab-contrib.github.io#15]
# Target

- The code repository: https://github.com/yuvipanda/jupyter-videochat
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab-videochat
- The python package on pypi.org (if available): https://pypi.org/project/jupyter-videochat
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyter-videochat-feedstock
- The documentation website (if available):

# Reason

https://github.com/yuvipanda/jupyter-videochat/issues/34 has some discussion. @bollwyvl has been the primary maintainer for a while, and moving it to an org is the way to go to get more contributors. @bollwyvl should have rights on the repo.

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [x] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [ ] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by bollwyvl** [comment]
I've been meaning to add some pytest/robot stuff to it, if that would help grease the wheels...

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/jupyter-videochat-demo also exists, providing a demo repo (similar to jupyterlab-demo)

**Comment by fcollonval** [comment]
Thanks for this proposal @yuvipanda 

One question: what is the difference between the demo repo and the binder setup in the extension repo?

I invite you as owner in this organization so you can transfer the project.
I also invite you on the npmjs jlab-contrib organization. So you should be able to add the jupyterlab-videochat to it (https://www.npmjs.com/settings/jlab-contrib/packages).
For pypi.org and conda, could you add me as co-owner of the package, please (my id is fcollonval).

**Comment by yuvipanda** [comment]
@fcollonval the demo repo is just pre-built to a certain version of the chat, so the lab build process doesn't need to happen for each binder launch - that can take a while. 

I moved the project, and added you as maintainer on PyPI. I didn't do the conda-forge feedstock, and so am not sure what to do there. I also couldn't figure out how to move the npm package? Any pointers there would be helpful!

THANK YOU!

**Comment by fcollonval** [comment]
Thanks for the quick reply. Here are the steps to add the package on npm organization:

To transfer the npm package to the _jlab-contrib_ organization go to that [page](https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access):

![image](https://user-images.githubusercontent.com/8435071/104559632-f26e1e80-5644-11eb-9264-9c8e9cd98417.png)

To add an existing package, you need to type its name in the input box next to + Add existing package button. Then click on that button.

**Comment by fcollonval** [comment]
For the conda package, I trust Nick to get things done :wink:

**Comment by bollwyvl** [comment]
Thanks for this all! I'll take a look when the dust settles later today,
but let me know if there's anything pressing.

**Comment by yuvipanda** [comment]
Aaah, thanks @fcollonval! I did that too now \o/

What do we do with the demo repo?

**Comment by fcollonval** [comment]
> What do we do with the demo repo?

I would rather keep things in the same repository. Is it ok for you @bollwyvl and @yuvipanda if we create a branch `demo` with those binder settings?

**Comment by yuvipanda** [comment]
@fcollonval sounds good to me!

**Comment by fcollonval** [comment]
> if there's anything pressing

None on my side.

**Comment by fcollonval** [comment]
:heavy_check_mark:
