### ISSUE TITLE
Activate/transfer jupyter-videochat RTD project 

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyterlab-contrib.github.io#16]
# Target

Enable a ReadTheDocs build for https://github.com/jupyterlab-contrib/jupyter-videochat/issues/39.

# Reason

To get CI-built docs without  a `gh-pages` deploy. I don't have GH perms to create webhook integration (but do have the URL, but _don't_ know if that's sensitive.... probably not).

# Checklist

- [x] You are owner of the RTD project you want to transfer

# Follow-on

This seems like a worthy thing to have an issue template for, with a better thought-out checklist :blush:. I think treating it like a transfer where "i, the issue reporter, already have the RTD name" is better than posting an issue about _creating_ the name... and then getting namesquatted.

Also the person signing up to be the "scribe" should be expected to bear the burden of anything harder than "click the activate webhook button" stuff: sending emails for feature flags, navigating the rtd.yml, etc.

**Comment by fcollonval** [comment]
@bollwyvl sorry I forget to update the permission after the project transfer in this organization. You should be able to do it now.

> Thanks for the template tip.

**Comment by bollwyvl** [comment]
Thanks, we're all good, have proceeded to waiting for feature flags.

I think once we have some good patterns, making docs part of the baseline will make sense, especially for those packages which can demonstrate at least some functionality in a JupyterLite environment (once that's more stable, and better handles packages-in-development).
