### ISSUE TITLE
Transfer of jupyterlab-vim extension

### ISSUE THREAD

**Issue by axelfahy** [jupyterlab-contrib/jupyterlab-contrib.github.io#17]
# Target

Vim keybindings for jupyterlab notebooks.

- The code repository: https://github.com/axelfahy/jupyterlab-vim
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/@axlair/jupyterlab_vim
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-vim/
- The conda-forge recipe on https://github.com/conda-forge (if available):
- The documentation website (if available):

# Reason

To avoid having only one maintainer and losing compatibility with next jupyterlab version. I forked the original extension (https://github.com/jwkvam/jupyterlab-vim) because it was not up-to-date with jupyterlab versions and I want to avoid the same issue for others if @ianhi or myself stop updating it. 

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [x] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks for starting this @axelfahy 

You should have received an invitation to join this organization as owner so that you can proceed with the repository transfer (I will reduce your rights afterwards).

Could you please add me to the PyPI project as owner?
Could you add the package on npm _jlab-contrib_ organization (you need to accept the invitation to join it)?

---

To add the npm package to the _jlab-contrib_ organization go to that [page](https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access):

![image](https://user-images.githubusercontent.com/8435071/104559632-f26e1e80-5644-11eb-9264-9c8e9cd98417.png)

To add an existing package, you need to type its name in the input box next to + Add existing package button. Then click on that button.

**Comment by axelfahy** [comment]
Thanks, @fcollonval, for the info. I am having an issue with the last step: I don't have the input box on the npm website:
![image](https://user-images.githubusercontent.com/7095119/132687984-46481828-d17f-47ad-a4e1-4296ec5ac8b4.png)

Am I missing something?

**Comment by fcollonval** [comment]
Sorry I needed to update your rights after you accepted the invitation. It should be appearing now.

**Comment by axelfahy** [comment]
All should be done, thanks a lot for the guidelines and the reactivity.

**Comment by fcollonval** [comment]
Thanks for granting me the access. As mentioned earlier, I switched you back as member of the organization but you should be now admin of the repository.

@ianhi do you want to get maintainer rights on the repository?

**Comment by ianhi** [comment]
> @ianhi do you want to get maintainer rights on the repository?

@fcollonval yes please that would be great. I've just enabled 2FA is there anything else I need to do?

**Comment by fcollonval** [comment]
You should have received an invitation for the GitHub repository as well as an invitation for the npm organization.
