### ISSUE TITLE
Transfer `jupyterlab-plugin-graph`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#19]
# Target

- The code repository: https://github.com/jtpio/jupyterlab-plugin-graph
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab-plugin-graph
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-plugin-graph/
- The conda-forge recipe on https://github.com/conda-forge (if available): Not available yet, but can easily be packaged afterwards
- The documentation website (if available):

# Reason

Follow-up to the move of other extensions, and to increase visibility.

The intended audience is more towards extension authors than regular end users though.

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [x] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @jtpio :+1: for the transfer

The steps to carry out:
- [ ] Transfer the git project
- [ ] Add the npm package to the jupyterlab-contrib organization on npm
- [ ] Add me to the PyPI project

**Comment by jtpio** [comment]
Conda Forge recipe coming in https://github.com/conda-forge/staged-recipes/pull/16221
