### ISSUE TITLE
Request to help support favorites and recents

### ISSUE THREAD

**Issue by mlhenderson** [jupyterlab-contrib/jupyterlab-contrib.github.io#27]
- Which repository do you want to maintain:
  - [x] jupyterlab-favorites, jupyterlab-recents
      - original maintainer for the repos before they were forked to jupyterlab-contrib 
  - [x] https://github.com/jupyterlab-contrib/jupyterlab-favorites
  - [x] https://github.com/jupyterlab-contrib/jupyterlab-recents
- What do you want to do (multiple choices accepted):
  - [x] Address reported issues and feature requests
  - [ ] Update an **Archived** repository to make it work on the latest JupyterLab version
  - [x] Improve an extension (if so please describe, what you want to achieve)
      - We are actively using both repos at NERSC for users, and it is likely that new features will either be requested from our users and/or that we will want to better integrate with new features in lab, such as RTC. 
- Which level of help, would you need (choose one of):
  - [ ] Total beginner but enthusiast (you are more than welcome and we will help in your learning of the Jupyter ecosystem)
  - [ ] Good reviews with tips would be appreciated
  - [x] I am an experienced developer with Jupyter ecosystem
       - Reviews and tips are still appreciated when they happen

**Comment by fcollonval** [comment]
Thanks @mlhenderson and I'm really happy to have you on board.

You should have received invitations for both repositories.
