### ISSUE TITLE
Transfer jupyterlab-link-share

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#3]
# Target

- The code repository: https://github.com/jtpio/jupyterlab-link-share
- The npm package on npmjs.com (if available): N/A - Since it's a simple extension for JupyterLab 3.0 and there isn't much too extend, it hasn't been published to npm. But it technically could be if needed.
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-link-share/
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyterlab-link-share-feedstock
- The documentation website (if available): https://github.com/jtpio/jupyterlab-link-share#jupyterlab-link-share

# Reason

`jupyterlab-link-share` is a simple extension to quickly share the link to a running Jupyter Server instance.

The main reason to move it would be to increase its visibility, as some people might be interested in adding it by default to their Binder config, so multiple people could easily collaborate on the same instance.

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [x] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @jtpio 

I invite you as owner in this organization so you can transfer the project.
I also invite you on the npmjs jlab-contrib organization. So you should be able to add the jupyterlab-kernelspy to it (https://www.npmjs.com/settings/jlab-contrib/packages).
For pypi.org and conda, if you are the sole maintainer, could you please add me as co-maintainer of the package (my id is fcollonval)?

**Comment by jtpio** [comment]
Thanks!

I believe most of the points above have now been addressed.

> So you should be able to add the jupyterlab-kernelspy to it (https://www.npmjs.com/settings/jlab-contrib/packages).

There is now an issue to consider publishing the extension to npm as well: https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/3

**Comment by fcollonval** [comment]
Thanks @jtpio
