### ISSUE TITLE
transfer DerThorsten/jupyterlab_pytutor/

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlab-contrib/jupyterlab-contrib.github.io#38]
# Target

- The code repository: https://github.com/DerThorsten/jupyterlab_pytutor/

# Reason
Give this repo better visibility and increase the change of usage

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [x] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [ ] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @DerThorsten you should have received an invitation to this organization. Once accepted you should be able to transfer your repository into this organization.

Was the package published on PyPI, conda and/or npmjs.org?

**Comment by jtpio** [comment]
> Was the package published on PyPI, conda and/or npmjs.org?

I don't think it has been published yet, But we can setup the releaser after the move to help with the release process.

**Comment by jtpio** [comment]
@DerThorsten you should now be able to transfer the repository.

**Comment by DerThorsten** [comment]
done

**Comment by jtpio** [comment]
thanks!
