### ISSUE TITLE
transfer ipylgbst

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlab-contrib/jupyterlab-contrib.github.io#41]
# Target
running a lego boost robot via web-bluetooth in the browser

- The code repository:https://github.com/DerThorsten/ipylgbst
- The npm package on npmjs.com (if available):
- The python package on pypi.org (if available): https://pypi.org/project/ipylgbst/
- The conda-forge recipe on https://github.com/conda-forge (if available):
- The documentation website (if available):

# Reason
better exposure, simplify releasing 

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [x] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x ] I don't care
- [ x] The code is available under a Open Source license
- [ ] A license file is present in the code repository
- [ ] The extension is working on at least JupyterLab 2.x
- [ ] The repository contains a README file describing:
  - [ x] The provided feature(s)
  - [ ] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x ] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x ] I certify the extension is not using exclusively paid-plan of any commercial service
- [x ] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @DerThorsten for proposing. Do you know if there is a jupyter widget organization similar to this one? I would prefer this organization to focus on JupyterLab / Notebook v7+ extensions and not mix with Jupyter Widgets.

cc @martinRenou who may know more about the landscape of Jupyter widgets.

**Comment by fcollonval** [comment]
Thanks @jtpio 

So let's move forward for lack of better solution.

**Comment by DerThorsten** [comment]
alright, and I make some screenshots +  videos of the robot in action

**Comment by DerThorsten** [comment]
done

**Comment by DerThorsten** [comment]
done
