### ISSUE TITLE
Set up `jupyterlab-contrib-bot` for releases

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#42]
Looks like this org already has a bot account: https://github.com/jupyterlab-contrib-bot

Maybe we could use it to make releases using the Jupyter Releaser v2 workflows?

This would help make releases for the projects under the `jupyterlab-contrib` GitHub organization.

Things to check:

- Push access on PyPI
- npm
- Admin access on the repos

cc @fcollonval who probably created this account

**Comment by jtpio** [comment]
So it looks like the `jupyterlab-contrib` org already has some secrets at the organization level:

![image](https://user-images.githubusercontent.com/591645/230581287-f9e691a1-d3c5-455b-809e-515b96ec91f3.png)


Maybe that means we could put the `jupyterlab-contrib-bot` secrets there, and they could be used from individual repos directly? 

Likely `ADMIN_GITHUB_TOKEN` and `NPM_TOKEN` would stay unchanged, and each repo could have a scoped `PYPI_TOKEN`? Or we define a `PYPI_TOKEN_MAP` at the org level.

**Comment by fcollonval** [comment]
ADMIN_GITHUB_TOKEN is mine for now (the bot may need to be granted more rights to set and valid admin token; did not check)
NPM_TOKEN is the bot
PYPI_TOKEN is the bot (valid for all PyPI packages)

**Comment by jtpio** [comment]
> the bot may need to be granted more rights to set and valid admin token; did not check)

Probably we could add the bot as "Admin" on the repos using the releaser v2 and I think it should work.

**Comment by fcollonval** [comment]
ADMIN_GITHUB_TOKEN is now the one of the bot as can be seen in https://github.com/jupyterlab-contrib/jupyterlab-vim/releases for example :arrow_right: closing this as resolved.
