### ISSUE TITLE
Transfer of repo `oscar6echo/react-auth-google-example`

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlab-contrib/jupyterlab-contrib.github.io#48]
# Target

Repo: https://github.com/oscar6echo/react-auth-google-example

This repo enables a JupyterLab user to authenticate with Google Identity services, and gives an example how to use it.   
It is constructed by the jupyterlab/extension-examples react-widget.  
Cf. its README.  

# Context

Described in this issue: https://github.com/jupyterlab/extension-examples/issues/242

**Comment by oscar6echo** [comment]
It seems to have worked: https://github.com/jupyterlab-contrib/react-auth-google-example

**Comment by fcollonval** [comment]
Hey @oscar6echo,

I reduced your rights at the organization to member and switch you role to admin on that specific repo.
