### ISSUE TITLE
Transfer jupyterlab-gitlab to jupyterlab-contrib organization

### ISSUE THREAD

**Issue by beenje** [jupyterlab-contrib/jupyterlab-contrib.github.io#49]
# Target

A JupyterLab extension for browsing GitLab repositories (in read-only mode).

This extension is based on [jupyterlab-github](https://github.com/jupyterlab/jupyterlab-github). All credit to the JupyterLab team, and especially [Ian Rose](https://github.com/ian-r-rose), for the github extension!

- The code repository: https://gitlab.com/beenje/jupyterlab-gitlab
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab-gitlab (not used anymore since 3.0.0)
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-gitlab
- The conda-forge recipe on https://github.com/conda-forge (if available): not available
- The documentation website (if available): not available

# Reason

I don't have much time to maintain this extension.
@krassowski  mentioned I could transfer it [here](https://github.com/jupyterlab/jupyterlab/issues/14590#issuecomment-1656427750). I think it can give the extension more visibility and make it easier to find people wanting to help.
@mahendrapaipuri already proposed to help.

# Checklist

- [X] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [X] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [X] I don't care
- [X] The code is available under a Open Source license
- [X] A license file is present in the code repository
- [X] The extension is working on at least JupyterLab 2.x
- [X] The repository contains a README file describing:
  - [X] The provided feature(s)
  - [X] A picture illustrating the feature(s)
  - [X] The available options/settings (if applicable)
  - [X] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [X] I certify the extension is not using exclusively paid-plan of any commercial service
- [X] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by mahendrapaipuri** [comment]
@beenje Thanks for setting up the issue. As @beenje said, I would be happy to take care of migration to `jupyterlab-contrib` namespace. Please let us know the next steps we need to do for transferring the repo.

Cheers!

**Comment by ian-r-rose** [comment]
I'm in favor of this, as I haven't had time to maintain it recently. Thanks to @beenje for continuing development and @mahendrapaipuri for taking over!

**Comment by fcollonval** [comment]
Thanks a lot all of you for that extension and for this proposal. I set up a GitHub repository in this organization for you to migrate the code in: https://github.com/jupyterlab-contrib/jupyterlab-gitlab

You should have received admin rights on it.

---

Regarding the PyPI and NPM packages, would you mind adding me as maintainer? My handle on both platforms is `fcollonval`.

**Comment by fcollonval** [comment]
Thanks @beenje - sorry to bother you for a final step (we are moving to use the org capability on PyPI and NPM and you are the first package transfer since that move). Would you mind adding the package:
- to the PyPI jupyterlab-contrib org: form accessible at the bottom of https://pypi.org/manage/organization/jupyterlab-contrib/projects
- to the NPM jlab-contrib org:
  1. Go to https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access
  2. Type `jupyterlab-gitlab` in the _Package_ input box
  3. Click _Add existing package_

**Comment by beenje** [comment]
> 2\. jupyterlab-gitlab

No problem. Done!

**Comment by fcollonval** [comment]
Thanks a lot @beenje 

Hopefully all rights are now properly set. Don't hesitate to open an issue and ping me in case I did something wrong that decreased your rights.
