### ISSUE TITLE
Transfer jupyterlab-night theme

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab-contrib/jupyterlab-contrib.github.io#50]
# Target

A JupyterLab dark theme that uses the same color palette as the Github dark theme

- The code repository: https://github.com/martinRenou/jupyterlab-night
- The npm package on npmjs.com (if available):https://www.npmjs.com/package/jupyterlab-night
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-night
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyterlab-night-feedstock
- The documentation website (if available): None

# Reason

I'd like it to be community driven

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [ ] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by jtpio** [comment]
Ping @martinRenou, just checking if you are still interested in transferring the repo.

**Comment by martinRenou** [comment]
Will do!

**Comment by martinRenou** [comment]
Agreed

**Comment by martinRenou** [comment]
Eventually I'd also like to transfer https://github.com/martinRenou/jupyterlab-day

**Comment by jtpio** [comment]
> Eventually I'd also like to transfer https://github.com/martinRenou/jupyterlab-day

That would be great!

And it would be nice to perform similar changes like https://github.com/martinRenou/jupyterlab-night/pull/16 and https://github.com/martinRenou/jupyterlab-night/pull/17 for that theme too.

**Comment by martinRenou** [comment]
Transfer done! https://github.com/jupyterlab-contrib/jupyterlab-night

> And it would be nice to perform similar changes like https://github.com/jupyterlab-contrib/jupyterlab-night/pull/16 and https://github.com/jupyterlab-contrib/jupyterlab-night/pull/17 for that theme too.

For sure!

**Comment by jtpio** [comment]
Thanks!

How about the transfer of the PyPI and npm packages? Not sure it show up under https://pypi.org/org/jupyterlab-contrib?

**Comment by martinRenou** [comment]
Indeed! I just did the PyPi transfer, although I'm not sure for the npm package, I invited `jupyterlab-contrib-bot` to be a maintainer

**Comment by jtpio** [comment]
For npm, as an owner of the `jlab-contrib` org, you should be able to add the npm package to the list here directly: https://www.npmjs.com/settings/jlab-contrib/packages

**Comment by martinRenou** [comment]
Thanks!
