### ISSUE TITLE
Transfer jupyterlab_spellchecker

### ISSUE THREAD

**Issue by ijmbarr** [jupyterlab-contrib/jupyterlab-contrib.github.io#6]
# Target
Transfer `jupyterlab_spellchecker`.

- The code repository: https://github.com/ijmbarr/jupyterlab_spellchecker
- The npm package on npmjs.com: https://www.npmjs.com/package/@ijmbarr/jupyterlab_spellchecker

# Reason
I no longer have time to contribute to developement of this extension. See discussion in https://github.com/ijmbarr/jupyterlab_spellchecker/issues/42

# Checklist

- [ x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [x] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment]
Thanks @ijmbarr 

You now have the rights to transfer the project into this organization (see [documentation](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account).

And you can also transfer the npm package to the _jlab-contrib_ organization by accessing that [page](https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access):

![image](https://user-images.githubusercontent.com/8435071/104559632-f26e1e80-5644-11eb-9264-9c8e9cd98417.png)

To add an existing package, you need to type its name in the input box next to + Add existing package button. Then click on that button.

**Comment by ijmbarr** [comment]
Transferred.

**Comment by fcollonval** [comment]
Awesome thanks a lot @ijmbarr. I will reduce your rights on the organization but not on the project to align with your availability for support. Let me know if you have question about that or if your rights have been reduced more than expected (I'll correct them).
