### ISSUE TITLE
I cannot open a file jupyter notebook

### ISSUE THREAD

**Issue by Abd1412** [jupyterlab-contrib/jupyterlab-contrib.github.io#65]
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 14:24:39.421 NotebookApp] Loading JupyterLab as a classic notebook (v6) extension.
[W 2024-02-01 14:24:39.424 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-02-01 14:24:39.424 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-02-01 14:24:39.426 LabApp] JupyterLab extension loaded from C:\Users\a-a-h\anaconda3\Lib\site-packages\jupyterlab
[I 2024-02-01 14:24:39.426 LabApp] JupyterLab application directory is C:\Users\a-a-h\anaconda3\share\jupyter\lab
[I 14:24:40.509 NotebookApp] The port 8888 is already in use, trying another port.
[I 14:24:40.509 NotebookApp] The port 8889 is already in use, trying another port.
[I 14:24:40.509 NotebookApp] The port 8890 is already in use, trying another port.
[I 14:24:40.509 NotebookApp] Serving notebooks from local directory: C:\Users\a-a-h
[I 14:24:40.509 NotebookApp] Jupyter Notebook 6.5.4 is running at:
[I 14:24:40.509 NotebookApp] http://localhost:8891/?token=cdd88cd09be8458e3cbe901fb6e387e4a8d13760e8e9a1c8
[I 14:24:40.509 NotebookApp]  or http://127.0.0.1:8891/?token=cdd88cd09be8458e3cbe901fb6e387e4a8d13760e8e9a1c8
[I 14:24:40.509 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:24:40.536 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/a-a-h/AppData/Roaming/jupyter/runtime/nbserver-1472-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=cdd88cd09be8458e3cbe901fb6e387e4a8d13760e8e9a1c8
     or http://127.0.0.1:8891/?token=cdd88cd09be8458e3cbe901fb6e387e4a8d13760e8e9a1c8

**Comment by krassowski** [comment]
@Abd1412 this is not the repository for Jupyter Notebook - I believe your question might be better answered on https://github.com/jupyter/notebook or https://discourse.jupyter.org/ - but please do provide more details on what do you mean by not being able to open a file (screenshots, steps to reproduce etc) when opening a new issue/topic over there.
