### ISSUE TITLE
Transfert jupyter-chat

### ISSUE THREAD

**Issue by brichet** [jupyterlab-contrib/jupyterlab-contrib.github.io#69]
# Target

- The code repository: https://github.com/QuantStack/jupyter-chat
- The npm package on npmjs.com (if available): none at the moment
- The python package on pypi.org (if available): none moment
- The conda-forge recipe on https://github.com/conda-forge (if available): none at the moment
- The documentation website (if available): none at the moment

# Reason

This project provides:
- a front end package that can be used in a Jupyter extension to include a chat
- a Jupyterlab extension that provides a chat panel

The first idea of this project was to extract the chat part of https://github.com/jupyterlab/jupyter-ai, to make it usable in other extensions.
See https://github.com/jupyterlab/jupyter-ai/issues/205 for more context.

Part of the code come from the *jupyter-ai* code base (already in Jupyterlab org), and *jupyter-ai* could make use of the front end package in a next future. 

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [ ] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [x] _optional_ The frontend code (Typescript/Javascript) is tested (**partially**)
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by martinRenou** [comment]
Thanks! Let's do it!

**Comment by martinRenou** [comment]
Done! https://github.com/jupyterlab-contrib/jupyter-chat

**Comment by brichet** [comment]
Thanks @martinRenou
