### ISSUE TITLE
Happy to help with spellchecker maintenance

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-contrib.github.io#7]
- Which repository do you want to maintain:
  - [ ] All
  - [x] https://github.com/jupyterlab-contrib/jupyterlab_spellchecker
- What do you want to do (multiple choices accepted):
  - [ ] Address reported issues and feature requests
  - [ ] Update a **Archived** repository to make it work on the latest JupyterLab version
  - [x] Improve an extension: language pack integration, improvements to spellchecker and custom word lists
- Which level of help, would you need (choose one of):
  - [ ] Total beginner but enthusiast (you are more than welcome and we will help in your learning of the Jupyter ecosystem)
  - [ ] Good reviews with tips would be appreciated
  - [x] I am a experienced developer with Jupyter ecosystem

**Comment by fcollonval** [comment]
Hey thanks a lot for the proposal. I invited you as Maintainer on the GitHub repo. And you should have received an invitation on the npmjs organization as well.

@ocordes if you want to become maintainer as well. Could you please fill in a [issue](https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/new?assignees=&labels=&template=help-with-maintenance.md&title=) too?
