### ISSUE TITLE
Change the minimal compatible version of Jupyterlab

### ISSUE THREAD

**Issue by brichet** [jupyterlab-contrib/jupyterlab-contrib.github.io#70]
Should we update the minimal compatible version of Jupyterlab to 3.x in the issue checklist ?

# Checklist

- ...
- [ ] The extension is working on at least JupyterLab 2.x
- ...

**Comment by jtpio** [comment]
Thanks @brichet for the suggestion. That sounds reasonable :+1:

**Comment by fcollonval** [comment]
I agree too. Would you mind opening a PR @brichet
