### ISSUE TITLE
Help with maintenance of jupyterlab_spellchecker

### ISSUE THREAD

**Issue by ocordes** [jupyterlab-contrib/jupyterlab-contrib.github.io#8]
- Which repository do you want to maintain:
  - [ ] All
  - [X] https://github.com/jupyterlab-contrib/jupyterlab_spellchecker
- What do you want to do (multiple choices accepted):
  - [X] Address reported issues and feature requests
  - [ ] Update a **Archived** repository to make it work on the latest JupyterLab version
  - [X] Improve an extension (if so please describe, what you want to achieve)
         - fix BUGs 
         - support more languages
         - integration with the language packages inside jupyterlab>3
- Which level of help, would you need (choose one of):
  - [ ] Total beginner but enthusiast (you are more than welcome and we will help in your learning of the Jupyter ecosystem)
  - [X] Good reviews with tips would be appreciated
  - [ ] I am a experienced developer with Jupyter ecosystem

**Comment by fcollonval** [comment]
Hey thanks a lot for the proposal. I invited you as Maintainer on the GitHub repo. 

Could you tell me your ID on [npmjs.com](https://www.npmjs.com) so I can give you the rights to publish the extension as well?

**Comment by ocordes** [comment]
Thnx for the invitation, on npmjs.com my ID is **ocordes** :-) Luckily I was able to get the same ID almost everywhere in the develoment sector ...

**Comment by fcollonval** [comment]
Nice ;-)

You should receive the npmjs invitation soon. Let me know if you did not.

**Comment by ocordes** [comment]
Everything is OK. It is correct that npmjs lists the extension with the same name @ijmbarr/jupyterlab_spellchecker as before? I checked the link which points to the old github page which is now redirected to the new one, which is nice. I'm just asking how much we have to do to adjust the package to his new institution.

**Comment by fcollonval** [comment]
> It is correct that npmjs lists the extension with the same name @ijmbarr/jupyterlab_spellchecker as before?

Yes this is a feature of npmjs that allow to group extension from various namespace into a common organization to ease access management (I wish so much Pypi as such feature...).
Personally I prefer to keep the previous name as it simplifies the update for users. And in this case, it is nice to keep the name of the original author.

So I'm closing this issue. And thanks again to come help with that extension.
