### ISSUE TITLE
Transfer `jupyterlab-day`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-contrib.github.io#82]
# Target

A JupyterLab dark theme that uses the same color palette as the Github dark theme

- The code repository: https://github.com/martinRenou/jupyterlab-day
- The npm package on npmjs.com (if available): N/A
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-day
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyterlab-day-feedstock
- The documentation website (if available): None

# Reason

I'd like it to be community driven

# Checklist

- [ ] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [x] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by jtpio** [comment]
cc @martinRenou if you are fine with the transfer, which would be similar to https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/50

Also it looks like https://www.npmjs.com/package/jupyterlab-day is not currently published to npm, so we wouldn't need to transfer it and can publish from the repo directly with the releaser.

**Comment by martinRenou** [comment]
Agreed! Thanks for suggesting

**Comment by martinRenou** [comment]
Done! https://github.com/jupyterlab-contrib/jupyterlab-day

**Comment by martinRenou** [comment]
Also transferred the PyPi package https://pypi.org/project/jupyterlab-day/

**Comment by jtpio** [comment]
Nice, thanks!

I'll set up the releaser on the repo.

**Comment by martinRenou** [comment]
Thanks!
